services:
  - type: web
    name: scrumboy-team
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: SQLITE_PATH
        value: ./app.db
      - key: SCRUMBOY_MODE
        value: full
